add 8 segment to display emulator
missionpinball/mpf pull request #1617
Opened 2021-11-08 04:57 UTC by borgdog

just a quick change to enable 8 segment virtual display

2021-11-08 23:47 UTC, jabdoa2 requested changes
Can you revert the other config_spec changes?

2021-11-08 23:47 UTC, jabdoa2 commented on mpf/config_spec.yaml
> -    max_reset_attempts: single|int|None
Not sure if you wanted to remove this.

2021-11-08 23:47 UTC, jabdoa2 commented on mpf/config_spec.yaml
> -    max_reset_attempts: single|int|None
Same here.

2021-11-08 23:47 UTC, jabdoa2 commented on mpf/config_spec.yaml
> -    empty_lock_devices_on_ball_end: single|bool|false
And here.

2021-11-08 23:50 UTC, borgdog commented
hmmm, I don't think I made those changes.. .I'll see if I can figure out
how to do that.


On Mon, Nov 8, 2021 at 3:47 PM jabdoa2 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Can you revert the other config_spec changes?
> ------------------------------
>
> In mpf/config_spec.yaml
> <https://github.com/missionpinball/mpf/pull/1617#discussion_r745178639>:
>
> > @@ -479,7 +479,6 @@ drop_targets:
>      enable_keep_up_events: event_handler|event_handler:ms|None
>      disable_keep_up_events: event_handler|event_handler:ms|None
>      ball_search_order: single|int|100
> -    max_reset_attempts: single|int|None
>
> Not sure if you wanted to remove this.
> ------------------------------
>
> In mpf/config_spec.yaml
> <https://github.com/missionpinball/mpf/pull/1617#discussion_r745178710>:
>
> > @@ -488,7 +487,6 @@ drop_target_banks:
>      __valid_in__: machine, mode
>      __type__: device
>      drop_targets: list|machine(drop_targets)|
> -    max_reset_attempts: single|int|None
>
> Same here.
> ------------------------------
>
> In mpf/config_spec.yaml
> <https://github.com/missionpinball/mpf/pull/1617#discussion_r745178783>:
>
> > @@ -1019,7 +1017,6 @@ multiball_locks:
>      priority: single|int|1
>      reset_all_counts_events: event_handler|event_handler:ms|None
>      reset_count_for_current_player_events: event_handler|event_handler:ms|None
> -    empty_lock_devices_on_ball_end: single|bool|false
>
> And here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/missionpinball/mpf/pull/1617#pullrequestreview-800714162>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGH7XMBKSLWEQO7TSX3C6FTULBORXANCNFSM5HRXO53A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-09 00:30 UTC, borgdog commented
I checked the box for allow edits from maintainers, but I do not know how to edit or revert the changes not wanted.  Sorry, very new to github and not a developer.

2021-11-09 08:02 UTC, jabdoa2 commented
> I checked the box for allow edits from maintainers, but I do not know how to edit or revert the changes not wanted. Sorry, very new to github and not a developer.

Dont worry. Will have a look later

2021-11-15 00:19 UTC, jabdoa2 approved these changes

2021-11-17 21:36 UTC, merged