score reels no longer activate chime on score reset.
missionpinball/mpf pull request #1784
Opened 2024-03-22 11:38 UTC by mrechte

This is to avoid noise during score reset.

2024-06-10 20:36 UTC, avanwinkle requested changes
Thank you for the improvement! I think it can be abstracted a little more to be useful in a wider range of situations, but it's a great fix!

2024-06-10 20:36 UTC, avanwinkle commented on mpf/devices/score_reel.py
> +                self.machine.events.post('reel_{}_advancing'.format(self.name))
This is a nice fix, but limited to your specific application. An alternative approach would be to post the event with an argument like `reset: true` to indicate whether the reel is resetting or not. This way there's still an event for people who want/need to know the advancement of the reel, and chimes can be made conditional on that argument to determine whether to chime or not.

2024-06-10 20:36 UTC, avanwinkle commented on mpf/devices/score_reel_group.py
> +    def set_value(self, value, quiet=False):
Aligned with my previous comment, changing the argument from `quiet` to `is_reset` will provide usecase-independent context and help future developers understand what's happening.

2024-06-12 15:55 UTC, mrechte commented on mpf/devices/score_reel_group.py
> +    def set_value(self, value, quiet=False):
Hello. Please could you help me ?
Everything starts from the score_reel_controller, that will call set_value() of ScoreReelGroup class in 3 situations:
1. _game_starting
2. _rotate_player
3. _score_change
If I understand correctly, ScoreReel would always 'post reel_{}_advancing', with an extra boolean argument 'reset'.
Then we would modify the chime handler of ScoreReelGroup, that would not pulse if reset is True.
How do I retrieve the reset argument in chime method ? Is it in kwargs, or do I just add a reset arg after chime ?

2024-06-17 18:28 UTC, avanwinkle commented on mpf/devices/score_reel_group.py
> +    def set_value(self, value, quiet=False):
When you post an event, you can include kwargs like so:
```
self.machine.events.post(f'reel_{self.name}_advancing', is_reset=False)
```

And then in an event listener, you can make it conditional:
```
event_player:
  reel_myreel_advancing{not is_reset}: play_chime
```

2026-02-15 06:20 UTC, bosh commented
We just added event management of chimes being enabled, via https://github.com/missionpinball/mpf/pull/1972/changes . I think it can cover the needs presented in this PR, so I'm proposing closing this one.

2026-02-28 18:05 UTC, closed without merging